import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Define your custom font
const airbnbCereal = localFont({
  src: [
    {
      path: "../font/AirbnbCereal_W_Lt.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/AirbnbCereal_W_Md.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../font/AirbnbCereal_W_XBd.otf",
      weight: "600",
      style: "semi-bold",
    },
    {
      path: "../font/AirbnbCereal_W_Bd.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-airbnb-cereal", // Optional: Define a CSS variable for the font
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${airbnbCereal.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
